---
title: Base
description: Base AME configuration
privilege: Admin
actions:
  - !run:
    currentDir: true
    exe: "DNET.bat"
    args: 
  - !run:
    currentDir: true
    exe: "REGI.bat"
  - !run:
    currentDir: true
    exe: "APPX.bat"
  - !run:
    currentDir: true
    exe: "EDGE.bat"
  - !run:
    currentDir: true
    exe: "EDGEX.bat"
  - !run:
    currentDir: true
    exe: "ONED.bat"
  - !run:
    currentDir: true
    exe: "PYTH.bat"
  - !run:
    currentDir: true
    exe: "AME-SFC-Modification-Script.cmd"
  - !run:
    currentDir: true
    exe: "TILE.bat"
  - !run:
    currentDir: true
    exe: "BANN.bat"
  - !run:
    currentDir: true
    exe: "SERV.bat"