title: services
description: services
privilege: Admin
actions:
  - !service:
    name: "DoSvc"
    state: stop
  - !service:
    name: "iphlpsvc"
    state: stop
  - !service:
    name: "Winmgmt"
    state: stop
  - !service:
    name: "ClipSVC"
    state: stop
  - !service:
    name: "DiagTrack"
    state: stop
  - !service:
    name: "RetailDemo"
    state: stop
  - !service:
    name: "diagnosticshub.standardcollector.service"
    state: stop
  - !service:
    name: "dmwappushservice"
    state: stop
  - !service:
    name: "InstallService"
    state: stop
  - !service:
    name: "LicenseManager"
    state: stop
  - !service:
    name: "lfsvc"
    state: stop
  - !service:
    name: "MapsBroker"
    state: stop
  - !service:
    name: "NetTcpPortSharing"
    state: stop
  - !service:
    name: "RemoteAccess"
    state: stop
  - !service:
    name: "RemoteRegistry"
    state: stop
  - !service:
    name: "SharedAccess"
    state: stop
  - !service:
    name: "StorSvc"
    state: stop
  - !service:
    name: "TrkWks"
    state: stop
  - !service:
    name: "UsoSvc"
    state: stop
  - !service:
    name: "WbioSrvc"
    state: stop
  - !service:
    name: "WMPNetworkSvc"
    state: stop
  - !service:
    name: "XblAuthManager"
    state: stop
  - !service:
    name: "XblGameSave"
    state: stop
  - !service:
    name: "XboxNetApiSvc"
    state: stop
  - !service:
    name: "wlidsvc"
    state: stop